apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: site-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "home.bentheelder.io"
    http:
      paths:
      - backend:
          serviceName: site-service
          servicePort: 8080

