# ingress for the site-service with tls via kube-lego
# obviously the hosts are specific to my site
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  # legacy name, this ingress does all ingress work, not just the site
  name: site-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/proxy-body-size: "0"
spec:
  tls:
  - hosts:
    - "bentheelder.io"
    - "code.bentheelder.io"
    - "docker.bentheelder.io"
    secretName: site-ingress-tls
  rules:
  - host: "bentheelder.io"
    http:
        paths:
        - path: /
          backend:
            serviceName: site-service
            servicePort: 8080
  - host: "code.bentheelder.io"
    http:
        paths:
        - path: /
          backend:
            serviceName: gogs-service
            servicePort: 3000
  - host: "docker.bentheelder.io"
    http:
        paths:
        - path: /
          backend:
            serviceName: docker-registry-service
            servicePort: 5000
